### Obtener todas las fotos

GET http://localhost:8080/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjUsImlhdCI6MTc0ODUzNjY3MCwiZXhwIjoxNzQ4NTcyNjcwfQ.WacfSNTbBZL5yi_WWmv82awAz2hqh3CE6kulxwumSso
Accept: application/json

### Obter foto por Id

GET http://localhost:8080/photo/4

### Crear foto

POST http://localhost:8080/createPhoto
Content-Type: application/json

{
    "title": "Amador",
    "description": "Personaje de la que se avecina",
    "date": "2020-04-20T20:30:00",
    "url": "https://amador.com",
    "visibility": "Public",
    "user_id": 2
}

### Borrar foto

DELETE http://localhost:8080/deletePhoto/1

### Actualizar foto

PUT http://localhost:8080/updatePhoto
Content-Type: application/json

{
    "photo_id": 10,
    "title": "Javi maroto",
    "description": "Personaje de la que se avecina",
    "date": "2020-04-20T21:30:00",
    "url": "https://amador.com",
    "visibility": "Public",
    "user_id": 2
}
