### Obtener todos los comentarios

GET http://localhost:8080/comments

### Obtener comentario por Id

GET http://localhost:8080/comments/2

### Crear comentario

POST http://localhost:8080/comments/create
Content-Type: application/json

{
  "text": "No me gusta la tortilla",
  "date": "2023-01-21T20:01:12",
  "user_id": 3,
  "photo_id": 1
}
 
### Actualizar comentario

PUT http://localhost:8080/comments/update
Content-Type: application/json

{
    "comment_id": 6,
    "text": "Viva españaaa!",
    "date": "2020-12-20T14:55:34",
    "user_id": 2,
    "photo_id": 6
}

### Borrar Comentario
DELETE  http://localhost:8080/comments/delete/7

