### Obtener todos los usuarios
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjUsImlhdCI6MTc0ODUzNjY3MCwiZXhwIjoxNzQ4NTcyNjcwfQ.WacfSNTbBZL5yi_WWmv82awAz2hqh3CE6kulxwumSso
Accept: application/json


### Crear Usuario

POST http://localhost:8080/create
Content-Type: application/json

{
  "firstName": "jeje",
  "lastName": "as",
  "telephone": "123456789",
  "email": "asdf@gallery.com",
  "username": "123",
  "password": "123",  
  "verified": false
}
### Iniciar sesion

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "123",
  "password": "123"
}

### Obetener usuario por Id

GET http://localhost:8080/user/2

### Borrar usuario por Id

DELETE http://localhost:8080/5

### Actualizar usuario

PUT http://localhost:8080
Content-Type: application/json

{
  "userId": 4,
  "firstName": "Cococdrilobombardino",
  "lastName": "Dofasfe",
  "telephone": "123456789",
  "email": "asdf@gallery.com",
  "username": "johndoasdfe",
  "password": "securepassword",
  "avatarUrl": "https://github.eii.us.es/avatars/u/40?s=460"
  
}

