GET http://localhost:8080/facilities

###

GET http://localhost:8080/facilities/1

###

POST http://localhost:8080/facilities/create
Content-Type: application/json

{
    "name": "Pista 3",
    "type": "padel",
    "is_active": "false"
}

###
PUT http://localhost:8080/facilities/update
Content-Type: application/json

{
    "facility_id": 6,
    "name": "Pista 3",
    "type": "padel",
    "is_active": "true"
}

###
DELETE http://localhost:8080/facilities/delete/6