GET http://localhost:8080/bookings

###
GET http://localhost:8080/bookings-with-facility/3

###

GET http://localhost:8080/booking-available-hours/1/2025-06-19

###

GET http://localhost:8080/booking-today

### Obtener booking por Id

GET http://localhost:8080/bookings/3

###

POST http://localhost:8080/booking/create
Content-Type: application/json

{
  "userId": 3,
  "facilityId": "3",
  "start_time": "2025-06-21T14:00:00",
  "end_time": "2025-06-21T15:30:00",
  "created_at": "2025-06-19T15:13:27.722Z"
}
###
PUT http://localhost:8080/booking/update
Content-Type: application/json

{
    "id": 1,
    "userId": 3,
    "facilityId": 1,
    "start_time": "2025-06-30T13:07:42",
    "end_time": "2025-05-30T13:07:52",
    "payment_status": "pending",
    "created_at": "2025-05-30T13:07:55",
    "cancelled_at": null
}


###

DELETE http://localhost:8080/booking/delete/1